[workspace]
members = [
    "modules/ai_module",
    "modules/coordination_module",
    "modules/zk_module",
    "modules/storage_module"
]

[patch.crates-io]
rand = { version = "0.8", features = ["std"] }
