[workspace]
members = [
    "modules/ai_module",
    "modules/coordination_module",
    "modules/coordination_module/json_comparator",
    "modules/coordination_module/fingerprint",
    "modules/zk_module",
    "modules/storage_module"
]
