[package]
name = "fingerprint"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "1.0"
dotenv = "0.15.0"
tokio = { version = "1.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"

[lib]
name = "fingerprint"
path = "src/lib.rs"