name: Rust CI

on:
  push:
    branches:
      - '*'  # Run on all branches
  pull_request:
    branches:
      - master  # Run when merging into master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Ensure full history is fetched

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable  # Install the stable version of Rust
        override: true

    - name: Debug - Print directory structure
      run: |
        pwd
        ls -R

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose
