name: Rust CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set correct working directory
      run: cd v1-playbase-core

    - name: Debug - Print directory structure
      run: |
        pwd
        ls -R

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build
      run: cargo build --verbose
      working-directory: ./v1-playbase-core

    - name: Run tests
      run: cargo test --verbose
      working-directory: ./v1-playbase-core
